Repository dmtcp/dmtcp, pull requests merged in 2019-08, with the labels that each got.

#753 SharedData: fixed header packing and member sizes.
  include/shareddata.h
  src/shareddata.cpp
Labels: 2.6.0, 3.0.0, bug

#741 test/plugin-init: INIT event before libc init'ed
  test/Makefile.in
  test/autotest.py
  test/plugin-init.cpp
Labels: 3.0.0, enhancement

#745 Record mutex owner, and handle robust mutexes
  src/plugin/pid/pid_mutexwrappers.cpp
  test/autotest.py
Labels: 2.6.0, 3.0.0, enhancement

#739 Fix dmtcp_dlvsym (handling of versioned symbols)
  src/dmtcp_dlsym.cpp
Labels: 2.6.0, 3.0.0, bug

#760 Fix test/syscall-tester; This test fails under root
  test/syscall-tester.c
Labels: 2.6.0, 3.0.0, bug

#767 Update changelog
  debian/changelog
Labels: 2.6.0, 3.0.0, debian
