Repository dmtcp/dmtcp, pull requests merged in 2019-12, with the labels that each got.

#795 autotest.py: fix commit 7e00e93 for syscall-tester
  test/autotest.py
Labels: 2.6.1, 3.0.0, bug

#797 Fix g++-9.2 compiler warnings in src/util_exec.cpp
  src/util_exec.cpp
Labels: 2.6.1, 3.0.0, bug

#801 Fix some minor typos (spelling, var. names)
  src/plugin/ipc/connectionlist.cpp
  src/plugin/pid/pidwrappers.cpp
  src/threadlist.cpp
Labels: 2.6.1, 3.0.0, enhancement

#803 More intutitive autotest format; ';' = new process
  test/autotest.py
Labels: 2.6.1, 3.0.0, enhancement

#806 connectionrewirer: Fix bug in creation of restore socket for IPv4 sockets
  src/plugin/ipc/socket/connectionrewirer.cpp
Labels: 2.6.1, 3.0.0, bug

#813 Fix commit d67aac7b (contrib/ckpttimer plugin); and bzero in jsocket.cpp -> memset
  contrib/ckpttimer/ckpttimer.cpp
  jalib/jsocket.cpp
Labels: 2.6.1, 3.0.0, bug

#808 presuspend-test: Fix compilation warning about implicit return type
  test/plugin/presuspend/presuspend.c
Labels: 3.0.0

#796 jalib/jalloc.c: 'size_t _blockSize;' wasn't initialized to 0
  jalib/jalloc.cpp
Labels: 2.6.1, 3.0.0, bug

#794 Fixes for aarch64
  src/execwrappers.cpp
  src/miscwrappers.cpp
  src/plugin/pid/pid_miscwrappers.cpp
Labels: 2.6.1, 3.0.0, bug

#798 Fix for DMTCP/Makefile.in for Python3
  Makefile.in
Labels: 2.6.1, 3.0.0, bug

#799 Add 'volatile' to: int dummy=1; while(dummy){};
  src/threadlist.cpp
Labels: 2.6.1, 3.0.0, bug

#800 syscall-tester.c: tmpnam() -> mkstemp()
  test/syscall-tester.c
Labels: 2.6.1, 3.0.0, enhancement

#802 aarch64 fixes for src/mtcp directory
  src/mtcp/mtcp_restart.c
  src/mtcp/restore_libc.c
Labels: 2.6.1, 3.0.0, bug

#804 Saving and restoring more RLIMIT_XXX values
  src/rlimitfloatenv.cpp
  test/syscall-tester.c
Labels: 2.6.1, 3.0.0, bug

#805 configure, and 'autotest hellompich-n[12]' now tests for MPICH3
  configure
  configure.ac
  test/autotest.py
  test/autotest_config.py.in
Labels: 2.6.1, 3.0.0, enhancement

#807 Complete 'make display-build-env' before the rest of the build in 'make'
  Makefile.in
Labels: 2.6.1, 3.0.0, enhancement
