Repository dmtcp/dmtcp, pull requests merged in 2019-09, with the labels that each got.

#755 Add gdbinit-example to util dir
  util/gdbinit-example
Labels: 2.6.0, 3.0.0

#758 MPIFIX workaround: handle GS in per-thread storage
  src/mtcp/mtcp_header.h
  src/mtcp/mtcp_restart.c
  src/mtcp/restore_libc.c
  src/mtcp/tlsutil.h
Labels: 3.0.0, enhancement

#759 Do not reset the NS database on checkpoint/resume (for 3.0)
  src/dmtcp_coordinator.cpp
Labels: 3.0.0, enhancement

#761 shareddata: Fix a race when multiple clients join simultaneously
  src/shareddata.cpp
Labels: 2.6.0, 3.0.0, bug

#766 Polishing test/plugin: README, Makefile
  test/plugin/README
  test/plugin/applic-delayed-ckpt/Makefile
  test/plugin/applic-initiated-ckpt/Makefile
Labels: 2.6.0, 3.0.0, enhancement

#577 Remove meaningless barrier
  src/plugin/svipc/sysvipc.cpp
  src/plugin/svipc/sysvipc.h
Labels: 3.0.0, refactoring

#769 Added DmtcpMutex and DmtcpRWLock functions.
  configure
  configure.ac
  include/config.h.in
  include/dmtcp.h
  include/futex.h
  include/virtualidtable.h
  jalib/jalib.cpp
  jalib/jalib.h
  jalib/jalloc.cpp
  src/Makefile.am
  src/Makefile.in
  src/execwrappers.cpp
  src/jalibinterface.cpp
  src/miscwrappers.cpp
  src/mutex.cpp
  src/nosyscallsreal.c
  src/plugin/ipc/connectionlist.cpp
  src/plugin/ipc/connectionlist.h
  src/plugin/ipc/file/fileconnlist.cpp
  src/plugin/ipc/file/filewrappers.h
  src/plugin/ipc/ipc.h
  src/plugin/svipc/sysvipc.cpp
  src/plugin/svipc/sysvipcwrappers.h
  src/plugin/timer/timer_create.cpp
  src/plugin/timer/timerlist.cpp
  src/plugin/timer/timerwrappers.h
  src/popen.cpp
  src/processinfo.cpp
  src/rwlock.cpp
  src/shareddata.cpp
  src/syscallsreal.c
  src/syscallwrappers.h
  src/threadlist.cpp
  src/threadsync.cpp
  test/autotest.py
Labels: 2.6.1, 3.0.0, enhancement

#770 Removed some unused wrappers from DMTCP.
  jalib/jalib.cpp
  jalib/jalib.h
  jalib/jalloc.cpp
  jalib/jsocket.cpp
  src/jalibinterface.cpp
  src/miscwrappers.cpp
  src/nosyscallsreal.c
  src/syscallsreal.c
  src/syscallwrappers.h
  src/util_misc.cpp
Labels: 2.6.1, 3.0.0, refactoring

#774 WSL-related changes for mtcp_restart.
  src/mtcp/mtcp_restart.c
  src/processinfo.h
Labels: 2.6.1, 3.0.0, bug

#775 3.0 fix restart commit
  src/mtcp/Makefile.debug
  src/mtcp/mtcp_restart.c
Labels: 2.6.1, 3.0.0

#779 Add presuspend example to test/plugin
  test/plugin/README
  test/plugin/presuspend/Makefile
  test/plugin/presuspend/README
  test/plugin/presuspend/applic.c
  test/plugin/presuspend/presuspend.c
Labels: 2.6.1, 3.0.0, enhancement

#763 restartscript: 'which dmtcp_discover_rm 2>/dev/null'
  src/restartscript.cpp
Labels: 2.6.0, 3.0.0, enhancement

#762 coordinator-api: Fix caching of coordinator host info
  src/coordinatorapi.cpp
Labels: 2.6.0, 3.0.0, bug

#776 Windows WSL: fix 'make check'
  src/mtcp/mtcp_restart.c
  src/plugin/ipc/connection.cpp
Labels: 2.6.1, 3.0.0, bug

#756 Minor polishing
  Makefile.in
  debian/rules
  src/dmtcp_coordinator.cpp
  src/dmtcp_restart.cpp
  src/mtcp/mtcp_restart.c
  src/mtcp/restore_libc.c
  test/autotest.py
  test/file2.c
  test/shared-memory2.c
Labels: 2.6.0, 3.0.0

#777 Minor polishing (part 2)
  debian/NEWS
  debian/rules
  plugin/modify-env/modify-env.c
  src/dmtcp_coordinator.cpp
  src/dmtcp_restart.cpp
  src/mtcp/mtcp_restart.c
  test/autotest.py
  test/file2.c
  test/shared-memory2.c
Labels: 3.0.0, enhancement
