Repository dmtcp/dmtcp, pull requests merged in 2022-02, with the labels that each got.

#939 Comp. warn's: dmtcp_coordinator.cpp, modify-env.c
  plugin/modify-env/modify-env.c
  src/dmtcp_coordinator.cpp
Labels: enhancement, 3.0.0

#940 Updated/Refactored TLS save/restore handling.
  include/dmtcp.h
  src/Makefile.am
  src/Makefile.in
  src/ldt.h
  src/mtcp/Makefile.in
  src/mtcp/mtcp_header.h
  src/mtcp/mtcp_restart.c
  src/mtcp/restore_libc.h
  src/mtcp/tlsutil.h
  src/syscallwrappers.h
  src/threadinfo.h
  src/threadlist.cpp
  src/threadlist.h
  src/tls.cpp
  src/tls.h
Labels: MANA

#948 Enhance and fix gdb-dmtcp-utils (data seg, perm)
  util/gdb-dmtcp-utils
Labels: enhancement

#950 Extend util/gdb-dmtcp-utils to work w/ core files
  util/gdb-dmtcp-utils
Labels: enhancement

#952 Polish some of the English text
  src/mtcp/mtcp_restart.c
  src/mtcp/sysdep/sysdep-x86_64.h
  util/readdmtcp.sh
Labels: enhancement

#953 Remove '#ifdef WSL' and WSL comments
  src/mtcp/mtcp_restart.c
  src/plugin/ipc/connection.cpp
Labels: enhancement

#958 Fix for commit 073e69a, to support gcc-4.8
  src/mtcp/sysdep/sysdep-x86_64.h
Labels: bug

#957 volatile -> volatile __attribute((aligned))
  include/dmtcp.h
  jalib/jalloc.cpp
  src/dmtcpworker.cpp
  src/threadlist.cpp
  test/plugin/presuspend/presuspend.c
  test/shared-memory1.c
Labels: bug

#658 dmtcpplugin: Make dmtcp_get_restart_env handle env of any size
  src/dmtcpplugin.cpp
Labels: enhancement, 3.0.0, 2.6.1

#962 Adding clone1 test (emulating child thread)
  test/Makefile.in
  test/autotest.py
  test/clone1.c
Labels: enhancement
